export const orderIngredientsInitState = {
    bun: [{calories: 420,
        carbohydrates: 53,
        fat: 24,
        image: "https://code.s3.yandex.net/react/code/bun-02.png",
        image_large: "https://code.s3.yandex.net/react/code/bun-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
        name: "Краторная булка N-200i",
        price: 1255,
        proteins: 80,
        type: "bun",
        __v: 0,
        _id: "60d3b41abdacab0026a733c6"}],
    main: [
        {calories: 3377,
            carbohydrates: 420,
            fat: 48,
            image: "https://code.s3.yandex.net/react/code/cheese.png",
            image_large: "https://code.s3.yandex.net/react/code/cheese-large.png",
            image_mobile: "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            name: "Сыр с астероидной плесенью",
            price: 4142,
            proteins: 84,
            type: "main",
            __v: 0,
            _id: "60d3b41abdacab0026a733d4"},
        {calories: 420,
            carbohydrates: 33,
            fat: 244,
            image: "https://code.s3.yandex.net/react/code/meat-02.png",
            image_large: "https://code.s3.yandex.net/react/code/meat-02-large.png",
            image_mobile: "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
            name: "Мясо бессмертных моллюсков Protostomia",
            price: 1337,
            proteins: 433,
            type: "main",
            __v: 0,
            _id: "60d3b41abdacab0026a733c9"}
    ],
    sauce: [{calories: 30,
        carbohydrates: 40,
        fat: 20,
        image: "https://code.s3.yandex.net/react/code/sauce-02.png",
        image_large: "https://code.s3.yandex.net/react/code/sauce-02-large.png",
        image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
        name: "Соус Spicy-X",
        price: 90,
        proteins: 30,
        type: "sauce",
        __v: 0,
        _id: "60d3b41abdacab0026a733cc"}],
    totalPrice: 8079
};